name: Check Broken Links

on:
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install markdown-link-check
      run: npm install -g markdown-link-check

    - name: Install Jekyll
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev
        gem install jekyll

    - name: Build the site
      run: |
        jekyll build

    - name: Check links in Markdown files
      run: |
        find . -name '*.md' | xargs -n1 markdown-link-check